CREATE TABLE tag
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tag_name VARCHAR(255),
    color    VARCHAR(255),
    CONSTRAINT pk_tag PRIMARY KEY (id)
);

CREATE TABLE genre
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    genre_name VARCHAR(255),
    CONSTRAINT pk_genre PRIMARY KEY (id)
);

create table details
(
    id       bigint generated by default as identity not null,
    date     varchar(255),
    detail   varchar(255),
    time     varchar(255),
    genre_id bigint                                  not null,
    foreign key (genre_id) references genre (id),
    tag_id   bigint                                  not null,
    foreign key (tag_id) references tag (id),
    CONSTRAINT pk_details PRIMARY KEY (id)

);


INSERT INTO genre (genre_name)
values ('TV'),
       ('Instagram'),
       ('Youtube'),
       ('Radio'),
       ('Live'),
       ('Release');

INSERT INTO tag (tag_name, color)
values ('yama', '#ff0000'),
       ('chine', '#ff66b8'),
       ('yuto', '#66ccff'),
       ('ari', '#ff8c1a'),
       ('ino', '#007bbb'),
       ('taka', '#9932cc'),
       ('hika', '#ffd900'),
       ('yabu', '#9cbb1c');

